### PR TITLE
feat: addd extra configuration for vite

### PR DESCRIPTION
**Pull request by Jordan-Hall**

### CODE REVIEW

**Comment by Jordan-Hall** [comment]
@DominikPieper realised the issue with e2e testing. Currently vite.config isn't being set in the build options. The build is relaying on vite finding the config itself. I've put a fix in place but maybe its worth making configFile a required field. We can always use the new base "plugin/vite" as the field we need

**Comment by DominikPieper** [comment]
@Jordan-Hall sounds good to me. I like explicit more than implicit self finding

**Comment by DominikPieper** [comment]
@Jordan-Hall I tried the dev executor, but seems like a problem with the printHttpServerUrls() function. We don't have e2e tests for the serve executors yet

**Comment by Jordan-Hall** [comment]
@DominikPieper  fixed in latest PR sorry

**Pull request merged**
