### PR TITLE
refactor(solid): remove Angular Devkit

### PR DESCRIPTION
**Pull request by DominikPieper**

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Great :) What is the process for getting the `solidjs` extension listed on https://nx.dev/community?

**Comment by kristianmandrup** [comment]
Oh, I see https://nx.dev/l/r/nx-plugin/overview#listing-your-nx-plugin

**Comment by kristianmandrup** [comment]
Any chance you could do this or would you rather that I fork Nx and follow the steps?

**Comment by DominikPieper** [comment]
@kristianmandrup I'll add all missing plugins

**Comment by kristianmandrup** [comment]
Still don't see the SolidJS plugin listed

**Comment by DominikPieper** [comment]
@kristianmandrup I did a PR but it’s just listed after its merged. That can take some days until someone takes a look at them

**Comment by kristianmandrup** [comment]
Alright :) Thanks for the update @DominikPieper

**Pull request merged**
