### PR TITLE
Fix missing dependency in sveltekit plugin

### LINKED ISSUE #799: Stencil | Svelte | Sveltekit | Solid | Vite | Vitest | React | Angular: <your title>
**Describe the bug**

Generating a new sveltekit project results in the following:

```
>  NX   Cannot find module '@angular-devkit/schematics'

   Require stack:
   - /Users/brian/Repos/bbot/node_modules/@nrwl/workspace/src/utils/ast-utils.js
   - /Users/brian/Repos/bbot/node_modules/@nrwl/workspace/src/utils/project-type.js
   - /Users/brian/Repos/bbot/node_modules/@nrwl/workspace/index.js
   - /Users/brian/Repos/bbot/node_modules/@nxext/sveltekit/src/generators/application/generator.js
   - /Users/brian/Repos/bbot/node_modules/nx/src/config/workspaces.js
   - /Users/brian/Repos/bbot/node_modules/nx/src/config/configuration.js
   - /Users/brian/Repos/bbot/node_modules/nx/src/command-line/generate.js
   - /Users/brian/Repos/bbot/node_modules/nx/src/command-line/nx-commands.js
   - /Users/brian/Repos/bbot/node_modules/nx/bin/init-local.js
   - /Users/brian/Repos/bbot/node_modules/nx/bin/nx.js
   Pass --verbose to see the stacktrace.
```

**To Reproduce**

- Install `@nxext/sveltekit` plugin in your workspace 
- Generate a new sveltekit project: `npx nx g @nxext/sveltekit:app foo`

**Expected behavior**
A project should be created without error.

**Additional context**
Observed in version 14.0.0-next.2. This might affect other plugins in the monorepo as well. Issue not detected in e2e tests presumably because it can resolve the dependency from the project node_modules.

### PR DESCRIPTION
**Pull request by bgourlie**
Fix #799

### CODE REVIEW

**Comment by algoflows** [comment]
Why isn't this merged yet?

**Comment by DominikPieper** [comment]
@algoflows the svelte kit plugin will get a whole rework now that the 1.0 of Sveltekit finally is there. I'll have to wait for a little until the official @nrwl/vite package got's an update to v4. After that the plugin get's some more love now where everything is a little more stable on Sveltekits side

**Comment by ty-ler** [comment]
@DominikPieper Looks like the @nrwl/vite package is [updated to v4 now!](https://github.com/nrwl/nx/pull/13800)

**Comment by DominikPieper** [comment]
@ty-ler  thanks. Yes that’s the commit but no release yet.

**Comment by pranav-js** [comment]
can this be fixed now?

**Pull request closed without merging**
