### PR TITLE
Chore/deprecated deps clean up

### PR DESCRIPTION
**Pull request by pawel-twardziak**
Hi @DominikPieper this is my proposal of skipping deprecated dependencies which causes peer deps conflicts while installing the plugin
What are your thoughts? Can we proceed this?

### CODE REVIEW

**Comment by DominikPieper** [comment]
Hey, @pawel-twardziak, looks good. Do you know, is the Svelte support removed completely? I cant find anything anymore on the Stencil homepage. If yes, don't comment it out, remove it :-)
And there are linting error :-)

**Comment by pawel-twardziak** [comment]
Hi @DominikPieper :) as I found this https://www.npmjs.com/package/@stencil/svelte-output-target deprecated and not being maintaned for 4 years, I assume we can skip it as this causes dependency conflicts :)
Oh, I forgot to lint it, will do!

**Comment by DominikPieper** [comment]
Hey, yes than remove it. Even if it’s a breaking thing, but it’s just for generating. The generation isn‘t used for build and so on, I would say it’s just halfway breaking. If the stencil tooling dropping support we should do too

**Comment by pawel-twardziak** [comment]
Ok, will remove. By saying I see it a BREAKING CHANGE I mean this https://www.npmjs.com/package/@stencil/eslint-plugin (changed it to @stencil-community/eslint-plugin) - this will break eslin rules so they stop working.
But, we could prepare a migration script for that - what do you think @DominikPieper ?

**Comment by DominikPieper** [comment]
Yes a migration would be great :)

**Comment by DominikPieper** [comment]
Sounds good :)

**Comment by pawel-twardziak** [comment]
Hi @DominikPieper I am finishing up the PR. Quick question: what the next version are we gonna release? 19.1.0 or 20.00?
I am asking in terms of the migration.
obraz

**Comment by DominikPieper** [comment]
Hi @pawel-twardziak,
we would go with 19.x. I used the major version to signal Nx compat version. 
So Nx 19.x our package 19.x

Minor and Patch for our own version tracking. Thats easier that store a version compat table ^^'

**Comment by pawel-twardziak** [comment]
Ok @DominikPieper :) does it mean I should set `version: 19.x` instead of the `version: 19.1.0` in the generator declaration?

**Comment by DominikPieper** [comment]
No I mean, you could use 19.1.0 and once Nx 20 is released we use 20.0.0 as a new starting point. After that we go with 20.0.1 or 20.1.0 and so on.

**Comment by pawel-twardziak** [comment]
Hmmm as the offcial NX dosc says:

this:
```JSON
{
  "generators": {
    "change-executor-name": {
      "version": "2.0.1",
      "description": "Changes the executor name from oldExecutorName to newExecutorName",
      "cli": "nx",
      "implementation": "./src/migrations/change-executor-name/change-executor-name"
    }
  }
}
```

is explained as follows:
```TEXT
This migration will be applied when the run nx migrate to move up past version 2.0.1 of our plugin.
```

so I assume that I shoud put `version: 19.0.0` so that starting from this one all the next versions will run the migration generator, right?

**Comment by pawel-twardziak** [comment]
Ok, but the docs says: `This migration will be applied when the run nx migrate to move up past version 2.0.1 of our plugin.` hmmm I still have doubts. You have done migration generator before, right?

**Comment by pawel-twardziak** [comment]
Anyway, I will use `19.1.0` for now :)

**Comment by DominikPieper** [comment]
Yes. Until now I hadn't problems yet. (except they changed something but I would doubt that).

**Comment by pawel-twardziak** [comment]
Great, thanks for consulting 👍 Let's keep going based on your experience

**Comment by pawel-twardziak** [comment]
btw, @DominikPieper is this feasible to assign me to this PR? :)

**Comment by pawel-twardziak** [comment]
btw, @DominikPieper is this feasible to assign me to this PR? :)

> btw, @DominikPieper is this feasible to assign me to this PR? :)
> 
> I've just pushed the migration. The last thing remains is testing the migration ;)

Ping ping :)

**Comment by pawel-twardziak** [comment]
The problem lies in this file `packages/eslint/src/executors/lint/lint.impl.ts`
obraz
This issue got fixed in [19.4.0](https://github.com/nrwl/nx/releases/tag/19.4.0)

do you want me to migrate NX workspace to 19.x? If yes, what `x` then? :)

**Comment by DominikPieper** [comment]
Maybe we should move to Nx 19.4 first, and integrate the PR's. After that go up to latest, ideally after #1103 is merged too. What do you think?

**Comment by pawel-twardziak** [comment]
I feel the same. Bumping up NX to 19.4 i more general task than this PR. Who is going to do the update to 19.4? :) Do you want my to do anything I just wait?

**Pull request merged**
