### PR TITLE
fix(vite): correct fileReplacements property names

### PR DESCRIPTION
**Pull request by iruszpel**
function `replaceFiles` expects input of type `{ file: string; with: string }` but current schema declares `{ replace: string; with: string }`

### CODE REVIEW

**Review by Jordan-Hall — APPROVED** [review]
Great spot. Thank you for finding this

**Comment by elizabethhart** [comment]
I've also run into this issue with file replacement. Was just about to open an issue on this, but noticed there's already a PR to fix! Are there plans to merge/release this change in the future?

**Review by Josh-Gotro — COMMENTED** [review]
I am also running into this file replacement issue and am grateful to see a PR already up to fix it. Any chance you plan on merging this in soon?

**Comment by Jordan-Hall** [comment]
@DominikPieper  I was thinking vite and NX now support just environmental vars. Should we follow in same direction?

**Comment by grundius** [comment]
Just ran into this myself. Great it is being fixed!

**Comment by grundius** [comment]
> @DominikPieper I was thinking vite and NX now support just environmental vars. Should we follow in same direction?

I actually use this feature to either inject a mock backend or a real backend depending on config. I could make the switch based on an environment var but that would mean some more complex logic as I do not want to package the mock backend, which includes `faker` into the production bundle. With file replacements I do not have to worry about that.

**Comment by Jordan-Hall** [comment]
Removing functionality in support of NX, Thank you @iruszpel  for this PR though, its much appreciated

**Pull request closed without merging**
