### PR TITLE
fix(stencil): keep existing entrypoint config

### PR DESCRIPTION
**Pull request by dschwank**
Hey!

Thanks for your great work. We use this plugin for a while already - recently we have the need to set a custom `types` entrypoint. While this works nicely in plain stencil repos, we noticed that it doesn't work within a NX monorepo. The reason is, that it will be overridden by the default config of this plugin.

To fix this, we propose to keep the existing `package.json` entrypoints and to only use the default values if the properties are not set.

While preparing this fix I noticed that the husky pre-commit hook is not working correctly - let me know if I should move the husky fix to a separate PR.

Happy to get your feedback!

### CODE REVIEW

**Comment by DominikPieper** [comment]
Hey, thanks for the PR. Looks good for me and seems like a good idea to keep existing 😅

**Comment by dschwank** [comment]
Thanks for the quick response @DominikPieper ! Could you have a look at the CI issues? It seems like the failing tests are not related to this PR - e.g.:

```sh
error svelte-jester@1.7.0: The engine "node" is incompatible with this module. Expected version ">= 14". Got "12.22.1"
```

If it helps I could also add some additional fixes to this PR.

**Comment by DominikPieper** [comment]
Ah the svelte checks are run cause of the husky changes. Global file changes lead to run all tests of all projects

**Comment by DominikPieper** [comment]
@dschwank unfortunately I can’t check anything right now, cause I’m not at home. This and next week I’ve holidays and no notebook here 😅

**Comment by dschwank** [comment]
> unfortunately I can’t check anything right now, cause I’m not at home. This and next week I’ve holidays and no notebook here 😅

@DominikPieper All good! Maybe I have some time to have a look at the other pipeline issues. Enjoy your holiday! 🌞

**Comment by dschwank** [comment]
> 2 workflows awaiting approval
> First-time contributors need a maintainer to approve running workflows.

Argh - security strikes back 😄 So this seems to be blocked then 😬

**Comment by DominikPieper** [comment]
Approve is easy from my phone but code things not 😂

**Comment by dschwank** [comment]
Locally the unit- & e2e-tests are working now again. I assume that there is still an encoding issue with windows, but lets see what the pipeline says 😉

**Comment by DominikPieper** [comment]
The damn windows is fighting me every time too 😂

**Comment by dschwank** [comment]
I removed the NX update to 12.4 due to the following bug: https://github.com/nrwl/nx/issues/6065

**Comment by dschwank** [comment]
@DominikPieper could you re-trigger the build? One unrelated test which worked in the commit before is now failing ... doesn't make any sense ...

**Comment by DominikPieper** [comment]
@dschwank  that’s the damn Windows test. It fails now and then. 😅 I‘d say the linux one is green that’s fine for now. I need some more time for the Windows ones. Failing for no reason every time for me too

**Comment by dschwank** [comment]
@DominikPieper Thanks for the support & merging! You will probably make a release when you are back from holiday and had time to check it - right?

Enjoy the rest of your holiday 🌞

**Comment by DominikPieper** [comment]
@dschwank thanks for the PR and my holidays are over now. There's 12.0.3 on npm since now https://www.npmjs.com/package/@nxext/stencil

**Pull request merged**
